apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: cip-key-secret
spec:
  images:
  - glob: "*docker.io/tanvika07/*"
  authorities:
  - key:
      secretRef:
        name: mysecret