apiVersion: apps/v1
kind: Deployment
metadata:
  name: unsigned-deployment
  labels:
    app: secure-webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-webpage
  template:
    metadata:
      labels:
        app: secure-webpage
    spec:
      containers:
      - name: secure-webpage
        image: docker.io/tanvika07/nginx-test:unsigned
        ports:
        - containerPort: 80
  